# Generated by Django 5.1.3 on 2024-11-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="department_name",
            field=models.ManyToManyField(blank=True, null=True, to="base.department"),
        ),
    ]
